<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Analytics.Infrastructure</RootNamespace>
    <AssemblyName>Analytics.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Analytics.Domain\Analytics.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.12.0" />
    <PackageReference Include="Common.Diagnostics" Version="0.4.0" />
    <PackageReference Include="Common.Diagnostics.Azure" Version="0.1.2" />
    <PackageReference Include="Common.Security" Version="0.1.1" />
    <PackageReference Include="MaxMind.GeoIP2" Version="6.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.10" />
  </ItemGroup>

</Project>
